language: python

python:
  - 3.4.5

services: sqlite3

env:
  - DJANGO=1.11.5

before_install:
  - export DJANGO_SETTINGS_MODULE=merenda.settings
  - export PYTHONPATH=$HOME/builds/fga-gpp-mds/fisCAE-2017-2
  - export PIP_USE_MIRRORS=true
  - export PYTHONPATH="/usr/local/lib/python3.4/dist-packages"

install:
  - pip install -r src/requirements.txt
  - pip install django==$DJANGO --quiet


script:
  - python manage.py migrate --noinput
  - cd-src.sh 
  - coverage run --source='.' manage.py test

after_success:
  - coveralls
